### PR TITLE
User experience of the cloudflare user experience that needs to be re -authenticated for the webpage authorization is required for sending messages

### PR DESCRIPTION
**Pull request by XiaoYingYo**
Optimizing ChatGPT requires cloudflare repeated verification user experience

### CODE REVIEW

**Comment by adamlui** [comment]
Hey I'm actually working on fixing this for my search scripts too!

**Comment by adamlui** [comment]
I tried pasting the code into Tampermonkey but it says 'Invalid userscript'

**Comment by XiaoYingYo** [comment]
> I tried pasting the code into Tampermonkey but it says 'Invalid userscript'

I can successfully use this script here, I use the `violent monkey`

Can you help you prompt, do the screenshot send it to me?

image

**Comment by adamlui** [comment]
Actually it wokred in Tampermonkey too when I clicked raw button on GitHub

**Comment by adamlui** [comment]
You should add

```
// @icon             https://www.google.com/s2/favicons?sz=48&domain=openai.com
// @icon64           https://www.google.com/s2/favicons?sz=64&domain=openai.com
```

**Pull request merged**
